In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
def DLUDisassembly(A):
    
    D_ = np.zeros(A.shape)
    L_ = np.zeros(A.shape)
    U_ = np.zeros(A.shape)

    for i, a in enumerate(A):
        for j, aa in enumerate(a):
            if i == j:
                D_[i][j] = aa
            elif i < j:
                U_[i][j]= aa
            else:
                L_[i][j] = aa
    return D_, L_, U_

In [60]:
def JacobiMethod(A, c, x0):
    x = []
    S = []
    D, L, U = DLUDisassembly(A)
    
    D_inv = np.linalg.inv(D)
    S = D_inv.dot(L + U)
    x1 = np.array([100, 100])
    
    while np.abs(np.linalg.norm(x1 - x0) ) > 10e-5:
        x0 = x1
        x1 = -D_inv.dot(L + U) .dot( x0 )+ D_inv.dot(c)
        x.append(x1)
        
        
    return x, S

In [61]:
x0 = np.array([0.2, 0.2])
A = np.array( [[5, -1],[1, 5]])
c = [3, 11]
aJ, Sj = JacobiMethod(A, c, x0)

In [62]:
aJ

[array([ 20.6, -17.8]),
 array([-2.96, -1.92]),
 array([0.216, 2.792]),
 array([1.1584, 2.1568]),
 array([1.03136, 1.96832]),
 array([0.993664, 1.993728]),
 array([0.9987456, 2.0012672]),
 array([1.00025344, 2.00025088]),
 array([1.00005018, 1.99994931]),
 array([0.99998986, 1.99998996])]

In [63]:
Sj

array([[ 0. , -0.2],
       [ 0.2,  0. ]])

In [64]:
def GaussSeidelMethod(A, c, x0):
    x = []
    S = []
    D, L, U = DLUDisassembly(A)
    print(D )
    print(L)
    print(D+L)
    DL_inv = np.linalg.inv(D + L)
    print(DL_inv)
    S = DL_inv.dot(U)
    
    x1 = [100, 100]
    while np.abs(np.linalg.norm(x1- x0)) > 10e-5:
        x0 = x1
        
        x1 = -DL_inv.dot(U) .dot( x0 )+ DL_inv.dot(c)
        x.append(x1)
        
        
    return x, S

In [65]:
aG, Sg = GaussSeidelMethod(A, c, x0)

[[5. 0.]
 [0. 5.]]
[[0. 0.]
 [1. 0.]]
[[5. 0.]
 [1. 5.]]
[[ 0.2   0.  ]
 [-0.04  0.2 ]]


In [66]:
aG

[array([20.6 , -1.92]),
 array([0.216 , 2.1568]),
 array([1.03136 , 1.993728]),
 array([0.9987456 , 2.00025088]),
 array([1.00005018, 1.99998996]),
 array([0.99999799, 2.0000004 ])]

In [68]:
Sg

array([[ 0.  , -0.2 ],
       [ 0.  ,  0.04]])